---
title: "Working notes"
output: github_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Dec. 14, 2023

-   Receive hard drive by mail sent by Birds Canada, David Bradley

### Dec 15, 2023

-   Data processing, organizing

-   All the recordings were put at the same folder

-   Organize recordings by ARU - found the \# doesn't fit the list on excel

-   Organize recordings by site, by ARU

-   There are some "un-categorized" recordings (can't set the location):

    -   ARU #6, date from 20200604 - 20200715

    -   ARU #11, date from 20190527 - 20190703

    -   ARU #12, date from 20190527 - 20190705

    -   ARU #16, date from 20170709 - 20170713

    -   ARU #25, date from 20200604 - 20200626

-   Questions:

    -   Holden Meadow only have 5 days of data instead of 10
    -   There are some data can't be opened! The data was damaged

-   Processed 3 sites, and got contacted by Birds Canada as the contract budget is not approved - stopped working on this project at the moment

### Dec. 18, 2023

-   Next steps:

    -   Finish running the rest of the recordings, site by site (need the location)

    -   Communicate the questions with Ghram

    -   Combine output from each site, each ARU

## Jan. 03, 2024

-   Got a message from David saying that the funding is available now!

## Jan. 14, 2024

-   Sent an email to David to update the progress

-   Ask about the corrupted files in four sites:

    1.  Baie Verte Port Elgin (site ID: NB43-03; ARU ID: 20)
    2.  Fredericton (site ID: NB05-04; ARU ID: 15)
    3.  Gagetown Island (site ID: NB11-06; ARU ID: 23)
    4.  Westcock (site ID: NB37-01; ARU ID: 21)

-   Ask about the file summarize method
